### ISSUE TITLE
Another set of packages that kill BiocCheck() before completion

### ISSUE THREAD

**Issue by hpages** [Bioconductor/BiocCheck#203]
Like for issue #199, the packages that trigger premature exit of `BiocCheck()` were identified by the [experimental BiocCheck automated builds](https://bioconductor.org/checkResults/devel/bioc-testing-LATEST/).

For 6 packages in these builds, `BiocCheck()` dies before completion with the following error:
```
* Checking vignette directory...
Error in match.arg(options$results, c("verbatim", "tex", "hide")) : 
  'arg' should be one of “verbatim”, “tex”, “hide”
```
The packages that trigger this error are: **AnnotationForge**, **BiocParallel**, **flowCore**, **genefilter**, **GenomeInfoDb**, and **mzID**. Note that for all these packages, the BiocCheck results are not available (`NA` status).

Thanks,
H.

**Comment by LiNk-NY** [comment]
This is due to a bug in identifying which vignettes should use `knitr::purl` vs `utils::Stangle`. I've fixed it in `1.39.6`.

**Comment by hpages** [comment]
Great! Thanks @LiNk-NY

**Comment by hpages** [comment]
Reopening since the issue persists for the **mzID** package:
```
> BiocCheck("mzID_1.41.0.tar.gz")
─ BiocCheckVersion: 1.39.18
─ BiocVersion: 3.19
─ Package: mzID
─ PackageVersion: 1.41.0
─ sourceDir: /tmp/RtmpP8RuC3/file1721246d197db/mzID
─ installDir: /tmp/RtmpP8RuC3/file172127b81a6d9
─ BiocCheckDir: /home/hpages/git.bioconductor.org/software/mzID.BiocCheck
─ platform: unix
─ isTarBall: TRUE

* Installing package...
* Checking for deprecated package usage...
  |======================================================================| 100%

  |======================================================================| 100%

* Checking for remote package usage...
* Checking for 'LazyData: true' usage...
* Checking version number...
* Checking for version number mismatch...
* Checking version number validity...
* Checking R version dependency...
* Checking package size...
* Checking individual file sizes...
* Checking biocViews...
* Checking that biocViews are present...
* Checking package type based on biocViews...
    Software
* Checking for non-trivial biocViews...
* Checking that biocViews come from the same category...
* Checking biocViews validity...
* Checking for recommended biocViews...
* Checking build system compatibility...
* Checking for blank lines in DESCRIPTION...
* Checking if DESCRIPTION is well formatted...
* Checking for proper Description: field...
* Checking for whitespace in DESCRIPTION field names...
* Checking that Package field matches directory/tarball name...
* Checking for Version: field...
* Checking for valid maintainer...
* Checking License: for restrictive use...
    * NOTE: License 'GPL (>= 2)' unknown; licenses cannot restrict use
* Checking for recommended DESCRIPTION fields...
    * NOTE: Provide 'URL', 'BugReports' field(s) in DESCRIPTION
* Checking for Bioconductor software dependencies...
    Bioconductor dependencies found in Imports & Depends (12%).
* Checking for pinned package versions in DESCRIPTION...
* Checking DESCRIPTION/NAMESPACE consistency...
* Checking .Rbuildignore...
* Checking for stray BiocCheck output folders...
* Checking vignette directory...
    * ERROR: 'VignetteBuilder' listed in DESCRIPTION but not found as
      'VignetteEngine' in any vignettes:
    * WARNING: Use RMarkdown instead of Sweave 'Rnw' vignettes.
    * WARNING: Package listed as VignetteEngine or VignetteBuilder but
      not currently Suggested.
Error in match.arg(options$results, c("verbatim", "tex", "hide")) : 
  'arg' should be one of “verbatim”, “tex”, “hide”
```

**sessionInfo():**
```
R Under development (unstable) (2024-01-02 r85764)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 23.10

Matrix products: default
BLAS:   /home/hpages/R/R-4.4.r85764/lib/libRblas.so 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: America/Los_Angeles
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocCheck_1.39.18

loaded via a namespace (and not attached):
 [1] rappdirs_0.3.3       utf8_1.2.4           generics_0.1.3      
 [4] bitops_1.0-7         RSQLite_2.3.4        magrittr_2.0.3      
 [7] fastmap_1.1.1        blob_1.2.4           processx_3.8.3      
[10] graph_1.81.0         DBI_1.2.1            ps_1.7.5            
[13] BiocManager_1.30.22  httr_1.4.7           purrr_1.0.2         
[16] fansi_1.0.6          stringdist_0.9.12    XML_3.99-0.16       
[19] codetools_0.2-19     httr2_1.0.0          cli_3.6.2           
[22] rlang_1.1.3          dbplyr_2.4.0         Biobase_2.63.0      
[25] bit64_4.0.5          withr_3.0.0          cachem_1.0.8        
[28] BiocBaseUtils_1.5.0  tools_4.4.0          parallel_4.4.0      
[31] memoise_2.0.1        dplyr_1.1.4          filelock_1.0.3      
[34] credentials_2.0.1    BiocGenerics_0.49.1  RUnit_0.4.32        
[37] curl_5.2.0           vctrs_0.6.5          R6_2.5.1            
[40] stats4_4.4.0         biocViews_1.71.1     BiocFileCache_2.11.1
[43] lifecycle_1.0.4      RBGL_1.79.0          bit_4.0.5           
[46] pkgconfig_2.0.3      callr_3.7.3          pillar_1.9.0        
[49] glue_1.7.0           gert_2.0.1           xfun_0.41           
[52] tibble_3.2.1         tidyselect_1.2.0     sys_3.4.2           
[55] knitr_1.45           compiler_4.4.0       askpass_1.2.0       
[58] openssl_2.1.1        RCurl_1.98-1.14     
```

**Comment by LiNk-NY** [comment]
Thanks for flagging. This is fixed in `1.39.20`. 
Their `%\\VignetteEngine{knitr}` threw off the `gsub` in the code. 
Should it be `%\\VignetteEngine{knitr::knitr}`? Either way, the code will catch `knitr` as the vignette engine.

**Comment by hpages** [comment]
Looks good: https://bioconductor.org/checkResults/devel/bioc-testing-LATEST/mzID/nebbiolo1-bioccheck.html

Thx!
